import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Cormorant } from "next/font/google";
import Footer from "./components/Footer";
import SnowfallEffect from "./components/SnowfallEffect";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cormorant = Cormorant({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cormorant",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={cormorant.className}
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} antialiased`}
      >
        <Navbar />
        <SnowfallEffect />
        {children}
        <Footer />
      </body>
    </html>
  );
}
